"""`kraken up` — plan-only by default, shared network `kraken`, no daemon."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from kraken.core.compose import ComposeError, find_plan, parse_compose, up
from kraken.core.network import SHARED_NETWORK, normalize_network_name, resolve_docker

BERTH_COMPOSE = """\
# generated by berth — do not put secrets here
services:
  api:
    image: nginx:alpine
    networks:
      - kraken
    ports:
      - "8080:80"
  worker:
    image: busybox:latest
    networks:
      - kraken
networks:
  kraken:
    name: kraken
    driver: bridge
"""


def _seed_berth(home: Path, compose: str = BERTH_COMPOSE) -> Path:
    d = home / ".kraken" / "data" / "berth"
    d.mkdir(parents=True, exist_ok=True)
    (d / "compose.yaml").write_text(compose, encoding="utf-8")
    (d / "project.json").write_text(json.dumps({"name": "demo"}), encoding="utf-8")
    return d


# --- network naming contract -------------------------------------------------


def test_shared_network_is_bare_kraken():
    assert SHARED_NETWORK == "kraken"
    assert normalize_network_name("kraken") == "kraken"
    assert resolve_docker({})["name"] == "kraken"


def test_arbitrary_labels_are_namespaced():
    assert normalize_network_name("lab") == "kraken_lab"
    assert normalize_network_name("kraken_ci") == "kraken_ci"
    assert normalize_network_name("") == "kraken"


def test_berth_network_survives_resolution():
    """berth emits bare `kraken`; core must not rewrite it to kraken_kraken."""
    net = resolve_docker({"network": "kraken"})
    assert net["name"] == "kraken"
    assert net["enabled"] is True


# --- offline policy ----------------------------------------------------------


def test_offline_blocks_remote_config_fetch(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("KRAKEN_HOME", str(tmp_path))
    cfg = tmp_path / "net.json"
    cfg.write_text('{"enabled": true, "name": "kraken_ci"}')
    monkeypatch.setenv("KRAKEN_DOCKER_CONFIG_URL", cfg.as_uri())

    monkeypatch.setenv("KRAKEN_OFFLINE", "1")
    off = resolve_docker({})
    assert off.get("fetch_skipped") == "offline"
    assert "fetch_error" not in off

    monkeypatch.delenv("KRAKEN_OFFLINE")
    on = resolve_docker({})
    assert on.get("source")


# --- compose parsing ---------------------------------------------------------


def test_parse_compose_reads_network_and_services():
    parsed = parse_compose(BERTH_COMPOSE)
    assert parsed["network"] == "kraken"
    assert parsed["network_driver"] == "bridge"
    assert parsed["service_names"] == ["api", "worker"]
    api = next(s for s in parsed["services"] if s["name"] == "api")
    assert api["networks"] == ["kraken"]
    assert api["ports"] == ["8080:80"]


def test_parse_compose_rejects_garbage():
    with pytest.raises(ComposeError):
        parse_compose("- just\n- a list\n")
    with pytest.raises(ComposeError):
        parse_compose("services: [oops]\n")
    with pytest.raises(ComposeError):
        parse_compose("services:\n  a: 1\nnetworks: nope\n")


# --- up() --------------------------------------------------------------------


def test_up_plans_without_starting_daemon(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("KRAKEN_HOME", str(tmp_path))
    _seed_berth(tmp_path)

    result = up({}, root=Path.cwd(), home=tmp_path)

    assert result["ok"] is True
    assert result["verb"] == "up"
    assert result["daemon"] is False
    assert result["network"]["name"] == "kraken"
    assert result["project"] == "demo"
    assert [s["name"] for s in result["services"]] == ["api", "worker"]
    assert result["orphan_networks"] == []
    assert result["public_ports"] == ["8080:80"]
    assert any("kraken up --start" in n for n in result["next"])


def test_up_reads_inline_compose(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("KRAKEN_HOME", str(tmp_path))
    result = up({"compose": BERTH_COMPOSE}, home=tmp_path)
    assert result["ok"] is True
    assert result["plan_source"] == "<inline>"
    assert result["network"]["name"] == "kraken"


def test_up_reads_explicit_file(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("KRAKEN_HOME", str(tmp_path))
    plan = tmp_path / "custom.yaml"
    plan.write_text(BERTH_COMPOSE, encoding="utf-8")
    result = up({"file": str(plan)}, home=tmp_path)
    assert result["ok"] is True
    assert result["plan_source"] == str(plan)


def test_up_without_plan_is_an_error_not_a_crash(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("KRAKEN_HOME", str(tmp_path))
    with pytest.raises(ComposeError):
        up({}, home=tmp_path)


def test_up_reports_orphan_networks(tmp_path: Path, monkeypatch):
    """A service on a different network would silently not join ours."""
    monkeypatch.setenv("KRAKEN_HOME", str(tmp_path))
    bad = BERTH_COMPOSE.replace("      - kraken", "      - somewhere_else")
    result = up({"compose": bad}, home=tmp_path)
    assert result["ok"] is False
    assert result["error"]["code"] == "network_mismatch"
    assert set(result["orphan_networks"]) == {"api", "worker"}


def test_up_start_is_refused_when_offline(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("KRAKEN_HOME", str(tmp_path))
    monkeypatch.setenv("KRAKEN_OFFLINE", "1")
    _seed_berth(tmp_path)
    result = up({}, root=Path.cwd(), home=tmp_path, start=True)
    assert result["ok"] is False
    assert result["error"]["code"] == "offline"
    assert result["daemon"] is False


def test_up_start_reports_missing_docker(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("KRAKEN_HOME", str(tmp_path))
    monkeypatch.delenv("KRAKEN_OFFLINE", raising=False)
    monkeypatch.setattr("kraken.core.compose._docker_available", lambda: False)
    _seed_berth(tmp_path)
    result = up({}, root=Path.cwd(), home=tmp_path, start=True)
    assert result["ok"] is False
    assert result["error"]["code"] == "no_docker"
    assert result["daemon"] is False


def test_find_plan_prefers_berth(tmp_path: Path, monkeypatch):
    monkeypatch.setenv("KRAKEN_HOME", str(tmp_path))
    _seed_berth(tmp_path)
    assert find_plan(tmp_path).name == "compose.yaml"
    assert find_plan(tmp_path, "berth").is_file()
    assert find_plan(tmp_path, "nope") is None


def test_up_never_writes_secrets_to_disk(tmp_path: Path, monkeypatch):
    """Plan-only must not mutate the arm's directory."""
    monkeypatch.setenv("KRAKEN_HOME", str(tmp_path))
    d = _seed_berth(tmp_path)
    before = sorted(p.name for p in d.iterdir())
    up({}, root=Path.cwd(), home=tmp_path)
    assert sorted(p.name for p in d.iterdir()) == before
